### ISSUE TITLE
How the data get populated in hotel reservation

### ISSUE THREAD

**Issue by Mellonta** [delimitrou/DeathStarBench#41]
The workload only contains the composition of different requests.
How about the data (hotel/inventory/user)?

**Comment by zyqCSL** [comment]
Data generation is embedded in cmd/*/*.db, like
https://github.com/delimitrou/DeathStarBench/blob/ef52862e8bc8649468bb443c18f29e12fb8b12f4/hotelReservation/cmd/geo/db.go#L93-L107.

**Comment by Fatahir** [comment]
did your services run properly? i dont know why my hotel reservation generate non 2xx or 3xx responses when workload is generated by wrk

**Comment by amoghavs** [comment]
Is it possible that the database initilization happens in other places too? 

I have disabled the default initialization and added some static data in each of the cmd/*/db.go code. I was expecting the code to pick up the static input I fed. But with the rebuilt code, I am still getting a lot of the initialization from before (which I hoped wasn't possible because of commenting the default intialization). 

It would be great if a rough program flow could be given on how the service comes up, where the DB is being initialized and how to change the input.
