### ISSUE TITLE
why does Qps tend to decrease when running "compose posts" workload?

### ISSUE THREAD

**Issue by mywulin** [delimitrou/DeathStarBench#59]
I ran the script 100 times below to check Qps ("Requests/sec") from the result, it seemed to be decreasing from 852 to 695. I am wondering where is bottleneck? But when I cleared the volume where mongodb used to store data, the Qps increased.

`./wrk -D exp -t 2 -c 2 -d 10 -L -s ./scripts/social-network/compose-post.lua http://localhost:8080/wrk2-api/post/compose -R 1 `

**Comment by cdelimitrou** [comment]
Because composePost involves the majority of microservices in the dependency graph; if you try one of the simpler queries, e.g., readTimeline, QPS will be better. Also, check that the CPU utilization of your containers is not saturated. If it is, you can update the allocation through the docker interface.
