### ISSUE TITLE
Jaeger collect the latency different from wrk2.

### ISSUE THREAD

**Issue by Cuiyus** [delimitrou/DeathStarBench#62]
In social-network, the latency of  requests(read-user-timeline)  collected by wrk is inconsistent with the delay collected by Jaeger.

n the data collected by jarger, part of the trace will reach the s level, and the delay information of wrk (0.txt) is the delay of ms level.

Do you encounter such a situation?

**Comment by gy1005** [comment]
We did observe the higher latency in wrk2 because of the client-side queueing. The latency of Jaeger could also be higher than that reported by wrk2 because we used async message queue in social-network. The compose-post request may return before it finishes writing to the home-timelines of all followers and tagged users.
