### ISSUE TITLE
Where are the .yaml files for kubernetes deployment? 

### ISSUE THREAD

**Issue by nfsp3k** [delimitrou/DeathStarBench#69]
Hello,

Why have the .yaml files for k8s deployment been removed from the master branch?
Aren't they correctly working now?

Thanks in advance!

**Comment by huikang** [comment]
I use https://kompose.io to translate the docker-compose file to a k8s yaml; it seems working.

**Comment by nfsp3k** [comment]
> I use https://kompose.io to translate the docker-compose file to a k8s yaml; it seems working.

Thank you @huikang! I'm going to try it!

**Comment by Aliasghar-Rahmanian** [comment]
Before doing dramatic upgrades in the apps, I used to run the apps on a local K8s cluster and they perfectly worked. After a while I needed to do more experiments with the apps but I realized that the new version for some reasons get **500 Internal Server Error** while sending requests to the app (apps are up and running on a local k8s cluster with virtual box VMs). Would you help us with that? I used those Yaml files for open shift to have them up and running on a local k8s cluster since in the recent upgrades there are no k8s-yaml files same as the prior versions.

**Comment by SolitaryThinker** [comment]
Hi, I have been trying to use https://kompose.io, however I'm running in to many issues. Which version of Kubernetes are you using?

**Comment by nfsp3k** [comment]
> Hi, I have been trying to use https://kompose.io, however I'm running in to many issues. Which version of Kubernetes are you using?

You can see the k8s YAML files in the following repository: https://github.com/Panlichen/DeathStarBench/tree/dev/socialNetwork
You might need some troubleshooting when applying it to the current repo.

**Comment by rajibhossen** [comment]
I used "kompose up" to deploy services in kubernetes. it deploys successfully, however, when I make a request in "http://127.0.0.1:8080", it returns connection refused. I tested with "docker-compose up", everything works fine. any workaround for kubernetes?
